Traceback (most recent call last):
  File "02_acquire_app_info.py", line 67, in validate_parsed_data
    assert data['details']['data'], 'data is empty'
AssertionError: details success is false
