Traceback (most recent call last):
  File "02_acquire_app_info.py", line 67, in validate_parsed_data
    def validate_parsed_data(appid, data):
AssertionError: details success is false
